MAINNET_PORT = 18981
TESTNET_PORT = 28981

LOCAL_ADDRESS = "127.0.0.1"

LOCAL_DAEMON_ADDRESS_MAINNET = "{}:{}".format(LOCAL_ADDRESS, MAINNET_PORT)
LOCAL_DAEMON_ADDRESS_TESTNET = "{}:{}".format(LOCAL_ADDRESS, TESTNET_PORT)

DAEMON_RPC_URL = "http://{}/json_rpc"
